server:
  port: 9999

mybatis:
  config-location: classpath:mybatis-config.xml

security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_order
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp